import Head from "next/head";

type LayoutProps = {
  children: React.ReactNode;
};

const Layout = (props: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Facebluk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col min-h-screen">
        {props.children}
        <Footer />
      </main>
    </>
  );
};

const Footer = () => {
  return (
    <div className="flex gap-4 text-xs text-neutral-100 bg-blue-500 p-2">
      <div>Contact</div>
      <a href="mailto:diegodevofficial@gmail.com" className="underline">
        diegodevofficial@gmail.com
      </a>
      <a
        href="https://www.linkedin.com/in/diego-castillo1/"
        target="_blank"
        className="underline"
      >
        https://www.linkedin.com/in/diego-castillo1/
      </a>
    </div>
  );
};

export default Layout;
